"""
News & Sentiment Collector — Phase A contextual data.
Uses yfinance built-in news + LLM-based sentiment analysis.
LLM is used ONLY for reasoning (sentiment), NOT for calculation.
"""
import yfinance as yf
from typing import Dict, List

from data_collection.yahoo_client import get_news


class NewsSentimentCollector:
    """Collects recent news and generates sentiment analysis via LLM."""

    def __init__(self, ticker: str):
        self.ticker = ticker.upper()
        self.stock = yf.Ticker(self.ticker)

    def get_recent_news(self) -> List[Dict]:
        """Fetch latest news from Yahoo Finance (dynamically)."""
        try:
            news = get_news(self.stock, self.ticker, count=5, tab="news") or []
        except Exception:
            news = []

        formatted = []
        for item in news[:5]:
            content = item.get("content", {}) or {}
            provider = content.get("provider", {}) or {}
            link = (content.get("clickThroughUrl") or {}).get("url") or (content.get("canonicalUrl") or {}).get("url")
            if not content.get("title") and not link:
                continue
            formatted.append(
                {
                    "title": content.get("title", ""),
                    "summary": content.get("summary", ""),
                    "publisher": provider.get("displayName", ""),
                    "link": link,
                    "published_at": content.get("pubDate"),
                    "type": content.get("contentType", ""),
                }
            )
        return formatted

    def analyze_sentiment_with_llm(self, news_items: List[Dict], llm) -> Dict:
        """
        Use LLM to analyze news sentiment.
        NOTE: This is LLM REASONING, not deterministic calculation.
        The LLM is explicitly used here for qualitative analysis only.
        """
        if not news_items:
            return {
                "sentiment": "neutral",
                "confidence": 0.5,
                "key_themes": [],
                "risk_signals": [],
                "note": "No recent news available for analysis",
            }
        headlines = "\n".join([f"- {n['title']}" for n in news_items])
        prompt = (
            f"As a senior equity research analyst, analyze the sentiment of these "
            f"recent headlines for {self.ticker}. Provide:\n"
            f"1. Overall sentiment: bullish / neutral / bearish\n"
            f"2. Confidence level: 0.0 to 1.0\n"
            f"3. Key themes (list of strings)\n"
            f"4. Risk signals (list of strings)\n\n"
            f"Headlines:\n{headlines}\n\n"
            f"Return a concise JSON object with keys: sentiment, confidence, "
            f"key_themes, risk_signals."
        )
        try:
            response = llm.invoke(prompt)
            content = response.content if hasattr(response, "content") else str(response)
            return {
                "llm_analysis": content,
                "raw_headlines": [n["title"] for n in news_items],
                "source_links": [n["link"] for n in news_items if n.get("link")],
                "note": "Sentiment generated by LLM reasoning, NOT deterministic calculation",
            }
        except Exception as e:
            return {
                "error": str(e),
                "raw_headlines": [n["title"] for n in news_items],
                "note": "LLM sentiment analysis failed; raw headlines preserved",
            }

    def collect(self, llm=None) -> Dict:
        """Full news + sentiment collection pipeline."""
        news = self.get_recent_news()
        result = {
            "ticker": self.ticker,
            "recent_news": news,
            "news_count": len(news),
            "data_source": "Yahoo Finance News API",
        }
        if llm is not None:
            result["sentiment_analysis"] = self.analyze_sentiment_with_llm(news, llm)
        return result
